// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/1/fizzbuzz": {
            "get": {
                "description": "get fizzbuzz computation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Computes Fizzbuzz",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit up to which fizzbuzz is computed",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "First divisor : all its multiples will be replaced by @fizz",
                        "name": "fizzer",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Second divisor: all its multiples will be replaced by @buzz",
                        "name": "buzzer",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Output for all numbers divisible by @fizzer (numbers divisible by both will output as the concatenation of @fizz@uzz)",
                        "name": "fizz",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Output for all numbers divisible by @buzzer (numbers divisible by both will output as the concatenation of @fizz@uzz)",
                        "name": "buzz",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/endpoint.EndpointError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/endpoint.EndpointError"
                        }
                    }
                }
            }
        },
        "/1/stats": {
            "get": {
                "description": "returns statistics about the most popular searches",
                "produces": [
                    "application/json"
                ],
                "summary": "Statistics endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.StatsResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "endpoint.EndpointError": {
            "type": "object",
            "properties": {
                "errorMessage": {
                    "type": "string"
                }
            }
        },
        "endpoint.StatsResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "request": {
                    "$ref": "#/definitions/service.FizzBuzzRequest"
                }
            }
        },
        "service.FizzBuzzRequest": {
            "type": "object",
            "properties": {
                "buzz": {
                    "type": "string"
                },
                "buzzer": {
                    "type": "integer"
                },
                "fizz": {
                    "type": "string"
                },
                "fizzer": {
                    "type": "integer"
                },
                "limit": {
                    "type": "integer"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "Fizzbuzz API",
	Description: "An API that computes fizzbuzzes",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
