definitions:
  endpoint.EndpointError:
    properties:
      errorMessage:
        type: string
    type: object
  endpoint.StatsResponse:
    properties:
      count:
        type: integer
      request:
        $ref: '#/definitions/service.FizzBuzzRequest'
    type: object
  service.FizzBuzzRequest:
    properties:
      buzz:
        type: string
      buzzer:
        type: integer
      fizz:
        type: string
      fizzer:
        type: integer
      limit:
        type: integer
    type: object
info:
  contact: {}
  description: An API that computes fizzbuzzes
  title: Fizzbuzz API
  version: "1.0"
paths:
  /1/fizzbuzz:
    get:
      consumes:
      - application/json
      description: get fizzbuzz computation
      parameters:
      - description: Limit up to which fizzbuzz is computed
        in: query
        name: limit
        required: true
        type: integer
      - description: 'First divisor : all its multiples will be replaced by @fizz'
        in: query
        name: fizzer
        required: true
        type: integer
      - description: 'Second divisor: all its multiples will be replaced by @buzz'
        in: query
        name: buzzer
        required: true
        type: integer
      - description: Output for all numbers divisible by @fizzer (numbers divisible
          by both will output as the concatenation of @fizz@uzz)
        in: query
        name: fizz
        required: true
        type: string
      - description: Output for all numbers divisible by @buzzer (numbers divisible
          by both will output as the concatenation of @fizz@uzz)
        in: query
        name: buzz
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/endpoint.EndpointError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/endpoint.EndpointError'
      summary: Computes Fizzbuzz
  /1/stats:
    get:
      description: returns statistics about the most popular searches
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/endpoint.StatsResponse'
      summary: Statistics endpoint
swagger: "2.0"
